name             'opsworks_kibana'
maintainer       'Adrien Brault'
maintainer_email 'adrien.brault@gmail.com'
license          'MIT'
description      'Kibana OpsWorks'
long_description 'Kibana OpsWorks'
version          '0.2.1'

depends 'yum-epel'
depends 'opsworks_utils'
depends 'ohai'
depends 'kibana_lwrp'
depends 'chamber-kibana'